version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Europe/London
   groups:
    rubocop:
       patterns:
         - "rubocop*"
    bundler:
      patterns:
        - "*"
       exclude-patterns:
         - "rubocop*"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
